server:
  port: 2345
  tomcat:
    max-swallow-size: 100MB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 7ad9f1175c13e4d3
    username: root
    url: jdbc:mysql://124:70:165:173:3306/InstaMesg?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.163.com
    username: instamesg@163.com
    password: OZJRYYCFCKFEIXDY
  file-storage:
    default-platform: webdav-1
    thumbnail-suffix: ".min.jpg"
    webdav:
      - platform: webdav-1
        enable-storage: true
        server: http://124.70.165.173:22300/
        user: Dusker
        password: Dusker2023
        base-path: instamesg
        storage-path: /
path:
  server: http://124.70.165.173:22300/